### ISSUE TITLE
Unsupported lambda property: BatchSize

### ISSUE THREAD

**Issue by dmarjenburgh** [brabster/crucible#126]
`BatchSize` is not a supported property on a lambda function. Should this be `ReservedConcurrentExecutions`?

The `:crucible.aws.lambda/batch-size` spec has a max of 10000, but the max reserved-concurrent-executions is 1000.

**Comment by dmarjenburgh** [comment]
I see it's a property of a lambda EventSourceMapping. So it looks like reserved-concurrent-executions is just a missing spec atm.

**Comment by brabster** [comment]
Yes @dmarjenburgh.

I often only added the properties I needed at the time, happy to merge PRs that add more!
