### ISSUE TITLE
Namespaced keyword maps more trouble than they're worth?

### ISSUE THREAD

**Issue by brabster** [brabster/crucible#18]
Having namespaced keyword maps for everything seems like a lot of effort to go to in every template for no obvious value - solving a problem that is unlikely to happen, and if it did it would be easy enough to solve? Maybe switch to non-namespaced keywords by default?

**Comment by milt** [comment]
For me, the use of qualified keywords + spec addresses a huge pain point in authoring templates: I can start with the key ns (or alias) and enumerate possible keys in my editor. It's been really hard to get a good workflow down that doesn't involve constant trips to the CF docs.

**Comment by brabster** [comment]
@milt first of all, thanks for being the first person I don't know in meat-space to say something here! (or in any of my repos, I think)

The autocompletion is a really nice bonus and I'll take your comment as an answer to my issue!

Issues and/or PRs most welcome if you think of any way to improve this!

Thanks again
